# Using Pandas and NumPy
## Portfolio and Risk
- Pandas Datareader
- Pandas
- Numpy
- Portfolio and return

### Resources
- Pandas Datareader
https://pandas-datareader.readthedocs.io/ (https://youtu.be/sgndYho8RyI)
- Pandas https://pandas.pydata.org (https://youtu.be/m8ahf_c9hEc)
- NumPy http://numpy.org (Focus here)

### Pandas Datareader & Pandas DataFrame

In [2]:
import numpy as np
import pandas_datareader as pdr
import datetime as dt
import pandas as pd

In [3]:
start = dt.datetime(2022, 1, 1)
data = pdr.get_data_yahoo("AAPL", start)

In [4]:
data.head()

High         Low        Open       Close       Volume  \
Date                                                                      
2022-01-03  182.880005  177.710007  177.830002  182.009995  104487900.0   
2022-01-04  182.940002  179.119995  182.630005  179.699997   99310400.0   
2022-01-05  180.169998  174.639999  179.610001  174.919998   94537600.0   
2022-01-06  175.300003  171.639999  172.699997  172.000000   96904000.0   
2022-01-07  174.139999  171.029999  172.889999  172.169998   86580100.0   

             Adj Close  
Date                    
2022-01-03  181.778397  
2022-01-04  179.471344  
2022-01-05  174.697418  
2022-01-06  171.781143  
2022-01-07  171.950928

In [5]:
data.index

DatetimeIndex(['2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06',
               '2022-01-07', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14', '2022-01-18', '2022-01-19',
               '2022-01-20', '2022-01-21', '2022-01-24', '2022-01-25',
               '2022-01-26', '2022-01-27', '2022-01-28', '2022-01-31',
               '2022-02-01', '2022-02-02', '2022-02-03', '2022-02-04',
               '2022-02-07', '2022-02-08', '2022-02-09', '2022-02-10',
               '2022-02-11', '2022-02-14', '2022-02-15', '2022-02-16',
               '2022-02-17', '2022-02-18', '2022-02-22', '2022-02-23',
               '2022-02-24', '2022-02-25', '2022-02-28', '2022-03-01',
               '2022-03-02', '2022-03-03', '2022-03-04', '2022-03-07',
               '2022-03-08', '2022-03-09', '2022-03-09'],
              dtype='datetime64[ns]', name='Date', freq=None)

In [6]:
data.dtypes

High         float64
Low          float64
Open         float64
Close        float64
Volume       float64
Adj Close    float64
dtype: object

In [7]:
type(data)

pandas.core.frame.DataFrame

### NumPy

In [8]:
data.to_numpy()

array([[1.82880005e+02, 1.77710007e+02, 1.77830002e+02, 1.82009995e+02,
        1.04487900e+08, 1.81778397e+02],
       [1.82940002e+02, 1.79119995e+02, 1.82630005e+02, 1.79699997e+02,
        9.93104000e+07, 1.79471344e+02],
       [1.80169998e+02, 1.74639999e+02, 1.79610001e+02, 1.74919998e+02,
        9.45376000e+07, 1.74697418e+02],
       [1.75300003e+02, 1.71639999e+02, 1.72699997e+02, 1.72000000e+02,
        9.69040000e+07, 1.71781143e+02],
       [1.74139999e+02, 1.71029999e+02, 1.72889999e+02, 1.72169998e+02,
        8.65801000e+07, 1.71950928e+02],
       [1.72500000e+02, 1.68169998e+02, 1.69080002e+02, 1.72190002e+02,
        1.06765600e+08, 1.71970901e+02],
       [1.75179993e+02, 1.70820007e+02, 1.72320007e+02, 1.75080002e+02,
        7.61383000e+07, 1.74857224e+02],
       [1.77179993e+02, 1.74820007e+02, 1.76119995e+02, 1.75529999e+02,
        7.48052000e+07, 1.75306641e+02],
       [1.76619995e+02, 1.71789993e+02, 1.75779999e+02, 1.72190002e+02,
        8.45058000e+07, 

In [9]:
arr = data.to_numpy()

In [10]:
arr.shape

(47, 6)

In [11]:
len(data)

47

In [12]:
arr[0]

array([1.82880005e+02, 1.77710007e+02, 1.77830002e+02, 1.82009995e+02,
       1.04487900e+08, 1.81778397e+02])

In [13]:
data.head(1)

High         Low        Open       Close       Volume  \
Date                                                                      
2022-01-03  182.880005  177.710007  177.830002  182.009995  104487900.0   

             Adj Close  
Date                    
2022-01-03  181.778397

In [14]:
arr.dtype

dtype('float64')

In [15]:
small = arr[:10, 0].copy()

In [16]:
small

array([182.88000488, 182.94000244, 180.16999817, 175.30000305,
       174.13999939, 172.5       , 175.17999268, 177.17999268,
       176.61999512, 173.77999878])

In [17]:
data.head()

High         Low        Open       Close       Volume  \
Date                                                                      
2022-01-03  182.880005  177.710007  177.830002  182.009995  104487900.0   
2022-01-04  182.940002  179.119995  182.630005  179.699997   99310400.0   
2022-01-05  180.169998  174.639999  179.610001  174.919998   94537600.0   
2022-01-06  175.300003  171.639999  172.699997  172.000000   96904000.0   
2022-01-07  174.139999  171.029999  172.889999  172.169998   86580100.0   

             Adj Close  
Date                    
2022-01-03  181.778397  
2022-01-04  179.471344  
2022-01-05  174.697418  
2022-01-06  171.781143  
2022-01-07  171.950928

In [18]:
np.max(small)

182.94000244140625

In [19]:
small.max()

182.94000244140625

In [20]:
small.argmax()

1

In [21]:
small

array([182.88000488, 182.94000244, 180.16999817, 175.30000305,
       174.13999939, 172.5       , 175.17999268, 177.17999268,
       176.61999512, 173.77999878])

In [22]:
small[small.argmax()]

182.94000244140625

In [23]:
np.log(small)

array([5.20883023, 5.20915824, 5.19390084, 5.16649881, 5.15985957,
       5.15039724, 5.16581397, 5.17716612, 5.1740005 , 5.15779012])

In [24]:
np.log(data)

High       Low      Open     Close     Volume  Adj Close
Date                                                                    
2022-01-03  5.208830  5.180153  5.180828  5.204062  18.464582   5.202788
2022-01-04  5.209158  5.188056  5.207462  5.191289  18.413761   5.190016
2022-01-05  5.193901  5.162727  5.190788  5.164329  18.364508   5.163055
2022-01-06  5.166499  5.145399  5.151556  5.147494  18.389231   5.146221
2022-01-07  5.159860  5.141839  5.152656  5.148482  18.276581   5.147209
2022-01-10  5.150397  5.124975  5.130372  5.148599  18.486146   5.147325
2022-01-11  5.165814  5.140610  5.149353  5.165243  18.148062   5.163970
2022-01-12  5.177166  5.163757  5.171166  5.167810  18.130398   5.166537
2022-01-13  5.174001  5.146273  5.169233  5.148599  18.252331   5.147325
2022-01-14  5.157790  5.142190  5.143650  5.153696  18.201965   5.152423
2022-01-18  5.150629  5.132322  5.144642  5.134621  18.325894   5.133348
2022-01-19  5.142131  5.111626  5.135798  5.113372  18.367438   5.112099
2022-01-20  5.133914  5.100963  5.117874  5.102971  18.330980   5.101698
2022-01-21  5.113974  5.089446  5.102424  5.090124  18.626466   5.088851
2022-01-24  5.089446  5.041488  5.075299  5.085248  18.904924   5.083975
2022-01-25  5.092277  5.056373  5.068778  5.073798  18.567361   5.072525
2022-01-26  5.102242  5.061455  5.096813  5.073234  18.500188   5.071961
2022-01-27  5.098890  5.064366  5.090370  5.070287  18.619159   5.069014
2022-01-28  5.137855  5.092522  5.110239  5.137738  19.008110   5.136464
2022-01-31  5.164786  5.132912  5.136739  5.163528  18.565141   5.162255
2022-02-01  5.163871  5.149295  5.159113  5.162555  18.272342   5.161282
2022-02-02  5.169802  5.155197  5.163356  5.169574  18.257153   5.168301
2022-02-03  5.171847  5.148192  5.161810  5.152713  18.308834   5.151440
2022-02-04  5.159630  5.139790  5.145632  5.149759  18.226992   5.149759
2022-02-07  5.158768  5.141371  5.152482  5.145516  18.162573   5.145516
2022-02-08  5.166784  5.144175  5.145923  5.163814  18.130719   5.163814
2022-02-09  5.174170  5.164214  5.170768  5.172074  18.082196   5.172074
2022-02-10  5.167525  5.144875  5.159860  5.148192  18.324895   5.148192
2022-02-11  5.153754  5.124202  5.149411  5.127766  18.406237   5.127766
2022-02-14  5.133325  5.115356  5.120207  5.129188  18.272013   5.129188
2022-02-15  5.153003  5.137268  5.141488  5.152077  17.951115   5.152077
2022-02-16  5.155255  5.136093  5.146622  5.150687  17.929288   5.150687
2022-02-17  5.146971  5.126758  5.141839  5.129188  18.058121   5.129188
2022-02-18  5.138970  5.113132  5.134739  5.119789  18.231609   5.119789
2022-02-22  5.116136  5.088522  5.105824  5.101816  18.328157   5.101816
2022-02-23  5.112891  5.073610  5.109213  5.075611  18.315422   5.075611
2022-02-24  5.092830  5.023881  5.027689  5.092154  18.765316   5.092154
2022-02-25  5.106672  5.080597  5.098890  5.105036  18.337019   5.105036
2022-02-28  5.108488  5.090247  5.094118  5.106672  18.368009   5.106672
2022-03-01  5.115596  5.087411  5.104126  5.094976  18.240051   5.094976
2022-03-02  5.120147  5.093443  5.102242  5.115356  18.194091   5.115356
2022-03-03  5.129366  5.109273  5.126758  5.113372  18.155131   5.113372
2022-03-04  5.109273  5.088213  5.102850  5.094793  18.243194   5.094793
2022-03-07  5.106067  5.069156  5.095956  5.070789  18.384212   5.070789
2022-03-08  5.093014  5.048573  5.067772  5.059044  18.691839   5.059044
2022-03-09  5.096262  5.071480  5.084381  5.093443  18.329454   5.093443
2022-03-09  5.096262  5.071480  5.084350  5.093443  18.331357   5.093443

In [25]:
data/data.shift()

High       Low      Open     Close    Volume  Adj Close
Date                                                                   
2022-01-03       NaN       NaN       NaN       NaN       NaN        NaN
2022-01-04  1.000328  1.007934  1.026992  0.987308  0.950449   0.987308
2022-01-05  0.984858  0.974989  0.983464  0.973400  0.951941   0.973400
2022-01-06  0.972970  0.982822  0.961528  0.983307  1.025031   0.983307
2022-01-07  0.993383  0.996446  1.001100  1.000988  0.893463   1.000988
2022-01-10  0.990582  0.983278  0.977963  1.000116  1.233142   1.000116
2022-01-11  1.015536  1.015758  1.019163  1.016784  0.713135   1.016784
2022-01-12  1.011417  1.023416  1.022052  1.002570  0.982491   1.002570
2022-01-13  0.996839  0.982668  0.998070  0.980972  1.129678   0.980972
2022-01-14  0.983920  0.995925  0.974741  1.005111  0.950881   1.005111
2022-01-18  0.992865  0.990181  1.000992  0.981106  1.131936   0.981106
2022-01-19  0.991538  0.979517  0.991196  0.978975  1.042419   0.978975
2022-01-20  0.991817  0.989394  0.982235  0.989653  0.964199   0.989653
2022-01-21  0.980257  0.988549  0.984669  0.987235  1.343778   0.987235
2022-01-24  0.975771  0.953173  0.973239  0.995136  1.321091   0.995136
2022-01-25  1.002834  1.014997  0.993501  0.988615  0.713507   0.988615
2022-01-26  1.010015  1.005095  1.028431  0.999437  0.935033   0.999437
2022-01-27  0.996654  1.002915  0.993578  0.997057  1.126338   0.997057
2022-01-28  1.039734  1.028557  1.020068  1.069778  1.475432   1.069778
2022-01-31  1.027297  1.041216  1.026854  1.026126  0.642127   1.026126
2022-02-01  0.999086  1.016518  1.022626  0.999027  0.746172   0.999027
2022-02-02  1.005948  1.005920  1.004253  1.007044  0.984926   1.007044
2022-02-03  1.002047  0.993019  0.998455  0.983280  1.053039   0.983280
2022-02-04  0.987857  0.991634  0.983952  0.997050  0.921417   0.998321
2022-02-07  0.999138  1.001582  1.006873  0.995765  0.937612   0.995765
2022-02-08  1.008048  1.002808  0.993463  1.018467  0.968648   1.018467
2022-02-09  1.007414  1.020242  1.025156  1.008294  0.952636   1.008294
2022-02-10  0.993377  0.980846  0.989151  0.976401  1.274685   0.976401
2022-02-11  0.986323  0.979539  0.989606  0.979782  1.084741   0.979782
2022-02-14  0.979778  0.991193  0.971218  1.001423  0.874394   1.001423
2022-02-15  1.019873  1.022154  1.021509  1.023152  0.725498   1.023152
2022-02-16  1.002255  0.998825  1.005147  0.998611  0.978409   0.998611
2022-02-17  0.991750  0.990709  0.995228  0.978731  1.137500   0.978731
2022-02-18  0.992031  0.986466  0.992925  0.990644  1.189446   0.990644
2022-02-22  0.977425  0.975690  0.971499  0.982188  1.101363   0.982188
2022-02-23  0.996760  0.985199  1.003394  0.974136  0.987346   0.974136
2022-02-24  0.980139  0.951487  0.921711  1.016680  1.568145   1.016680
2022-02-25  1.013939  1.058355  1.073797  1.012965  0.651618   1.012965
2022-02-28  1.001817  1.009697  0.995239  1.001638  1.031475   1.001638
2022-03-01  1.007133  0.997168  1.010058  0.988372  0.879890   0.988372
2022-03-02  1.004562  1.006050  0.998118  1.020588  0.955081   1.020588
2022-03-03  1.009261  1.015956  1.024819  0.998019  0.961789   0.998019
2022-03-04  0.980108  0.979160  0.976376  0.981592  1.092057   0.981592
2022-03-07  0.996799  0.981123  0.993130  0.976282  1.151445   0.976282
2022-03-08  0.987032  0.979628  0.972209  0.988324  1.360194   0.988324
2022-03-09  1.003254  1.023171  1.016748  1.034997  0.696014   1.034997
2022-03-09  1.000000  1.000000  0.999969  1.000000  1.001904   1.000000

In [26]:
data.head()

High         Low        Open       Close       Volume  \
Date                                                                      
2022-01-03  182.880005  177.710007  177.830002  182.009995  104487900.0   
2022-01-04  182.940002  179.119995  182.630005  179.699997   99310400.0   
2022-01-05  180.169998  174.639999  179.610001  174.919998   94537600.0   
2022-01-06  175.300003  171.639999  172.699997  172.000000   96904000.0   
2022-01-07  174.139999  171.029999  172.889999  172.169998   86580100.0   

             Adj Close  
Date                    
2022-01-03  181.778397  
2022-01-04  179.471344  
2022-01-05  174.697418  
2022-01-06  171.781143  
2022-01-07  171.950928

In [27]:
182.940002/182.880005

1.0003280675763322

In [28]:
np.sum(np.log(data/data.shift()))

High        -0.112568
Low         -0.108674
Open        -0.096478
Close       -0.110618
Volume      -0.133225
Adj Close   -0.109345
dtype: float64

In [29]:
np.log(data/data.iloc[0]).tail(1)

High       Low      Open     Close    Volume  Adj Close
Date                                                                   
2022-03-09 -0.112568 -0.108674 -0.096478 -0.110618 -0.133225  -0.109345

In [30]:
small.shape

(10,)

In [31]:
small

array([182.88000488, 182.94000244, 180.16999817, 175.30000305,
       174.13999939, 172.5       , 175.17999268, 177.17999268,
       176.61999512, 173.77999878])

In [32]:
small.reshape(2, 5)

array([[182.88000488, 182.94000244, 180.16999817, 175.30000305,
        174.13999939],
       [172.5       , 175.17999268, 177.17999268, 176.61999512,
        173.77999878]])

In [33]:
small.reshape(10, 1)

array([[182.88000488],
       [182.94000244],
       [180.16999817],
       [175.30000305],
       [174.13999939],
       [172.5       ],
       [175.17999268],
       [177.17999268],
       [176.61999512],
       [173.77999878]])

In [34]:
small.reshape(-1, 1)

array([[182.88000488],
       [182.94000244],
       [180.16999817],
       [175.30000305],
       [174.13999939],
       [172.5       ],
       [175.17999268],
       [177.17999268],
       [176.61999512],
       [173.77999878]])

### Portfolios

In [78]:
tickers = ['AAPL','MSFT', 'TWTR', 'IBM']

start = dt.datetime(2022, 1, 1)
end = dt.datetime.now()

df = pdr.get_data_yahoo(tickers, start)
df.drop_duplicates(subset=['High','Low','Open','Close','Volume','Adj Close'], keep='last')

KeyError: Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [81]:
# = ['AAPL','MSFT', 'TWTR', 'IBM']

#start = dt.datetime(2022, 1, 1)
#end = dt.datetime.now()

#data = pdr.get_data_yahoo(tickers, start)
#idx.duplicated(keep = first)

#I have really struggled trying to get the duplicated indices and how to drop then but i don't know why i does not repeat that error again and i haven't done any major changes'

NameError: name 'idx' is not defined

In [82]:
tickers = ['AAPL','MSFT', 'TWTR', 'IBM']
start = dt.datetime(2022, 1, 1)



data = pdr.get_data_yahoo(tickers, start)
data.duplicated()
#df.drop_duplicates(keep = False)

Date
2022-01-03    False
2022-01-04    False
2022-01-05    False
2022-01-06    False
2022-01-07    False
2022-01-10    False
2022-01-11    False
2022-01-12    False
2022-01-13    False
2022-01-14    False
2022-01-18    False
2022-01-19    False
2022-01-20    False
2022-01-21    False
2022-01-24    False
2022-01-25    False
2022-01-26    False
2022-01-27    False
2022-01-28    False
2022-01-31    False
2022-02-01    False
2022-02-02    False
2022-02-03    False
2022-02-04    False
2022-02-07    False
2022-02-08    False
2022-02-09    False
2022-02-10    False
2022-02-11    False
2022-02-14    False
2022-02-15    False
2022-02-16    False
2022-02-17    False
2022-02-18    False
2022-02-22    False
2022-02-23    False
2022-02-24    False
2022-02-25    False
2022-02-28    False
2022-03-01    False
2022-03-02    False
2022-03-03    False
2022-03-04    False
2022-03-07    False
2022-03-08    False
2022-03-09    False
2022-03-10    False
dtype: bool

In [83]:
data.head()

Attributes   Adj Close                                          Close  \
Symbols           AAPL        MSFT       TWTR         IBM        AAPL   
Date                                                                    
2022-01-03  181.778397  334.059265  42.660000  134.420822  182.009995   
2022-01-04  179.471344  328.331116  40.849998  136.377274  179.699997   
2022-01-05  174.697418  315.727173  39.500000  136.574890  174.919998   
2022-01-06  171.781143  313.232330  39.590000  133.729156  172.000000   
2022-01-07  171.950928  313.391998  39.669998  133.225235  172.169998   

Attributes                                           High              ...  \
Symbols           MSFT       TWTR         IBM        AAPL        MSFT  ...   
Date                                                                   ...   
2022-01-03  334.750000  42.660000  136.039993  182.880005  338.000000  ...   
2022-01-04  329.010010  40.849998  138.020004  182.940002  335.200012  ...   
2022-01-05  316.380005  39.500000  138.220001  180.169998  326.070007  ...   
2022-01-06  313.880005  39.590000  135.339996  175.300003  318.700012  ...   
2022-01-07  314.040009  39.669998  134.830002  174.139999  316.500000  ...   

Attributes        Low                    Open                         \
Symbols          TWTR         IBM        AAPL        MSFT       TWTR   
Date                                                                   
2022-01-03  42.480000  133.630005  177.830002  335.350006  43.500000   
2022-01-04  40.360001  135.899994  182.630005  334.829987  42.849998   
2022-01-05  39.450001  137.880005  179.610001  325.859985  40.799999   
2022-01-06  38.689999  132.509995  172.699997  313.149994  39.500000   
2022-01-07  39.320000  133.509995  172.889999  314.149994  39.650002   

Attributes                   Volume                                     
Symbols            IBM         AAPL        MSFT        TWTR        IBM  
Date                                                                    
2022-01-03  134.070007  104487900.0  28865100.0  14431900.0  4605900.0  
2022-01-04  136.100006   99310400.0  32674300.0  21422400.0  7300000.0  
2022-01-05  138.309998   94537600.0  40054300.0  22008600.0  8956900.0  
2022-01-06  138.199997   96904000.0  39646100.0  16613400.0  9908100.0  
2022-01-07  134.899994   86580100.0  32674000.0  14641200.0  5235900.0  

[5 rows x 24 columns]

In [84]:
data = data['Adj Close']

In [85]:
data.head()

Symbols           AAPL        MSFT       TWTR         IBM
Date                                                     
2022-01-03  181.778397  334.059265  42.660000  134.420822
2022-01-04  179.471344  328.331116  40.849998  136.377274
2022-01-05  174.697418  315.727173  39.500000  136.574890
2022-01-06  171.781143  313.232330  39.590000  133.729156
2022-01-07  171.950928  313.391998  39.669998  133.225235

In [87]:
portfolios = [.25, .15, .40, .20]
#percentage held in each stock respectively

In [88]:
np.sum(portfolios)

1.0

In [89]:
(data/data.iloc[0])*portfolios*100000

Symbols             AAPL          MSFT          TWTR           IBM
Date                                                              
2022-01-03  25000.000000  15000.000000  40000.000000  20000.000000
2022-01-04  24682.710837  14742.793420  38302.858528  20291.093505
2022-01-05  24026.152375  14176.848503  37037.037170  20320.496179
2022-01-06  23625.076796  14064.824554  37121.425499  19897.089508
2022-01-07  23648.427281  14071.993999  37196.435359  19822.112804
2022-01-10  23651.174273  14082.300076  37477.732174  19851.515477
2022-01-11  24048.130413  14114.115859  38124.706979  19533.961609
2022-01-12  24109.938791  14261.537572  37740.272052  19639.812142
2022-01-13  23651.174273  13657.953069  36286.920676  19811.821528
2022-01-14  23772.048234  13899.925949  36043.130581  19730.964743
2022-01-18  23322.895042  13561.612281  34974.214131  19544.252885
2022-01-19  22832.536964  13592.082422  35021.095741  19344.311981
2022-01-20  22596.285126  13514.562798  34955.460771  19232.581368
2022-01-21  22307.842531  13264.973753  32648.851214  19016.467972
2022-01-24  22199.328987  13280.208824  32873.887950  18938.550092
2022-01-25  21946.597293  12927.109546  32039.379551  20008.822391
2022-01-26  21934.234778  13295.443894  31523.674686  19738.313709
2022-01-27  21869.679407  13435.697533  31729.958062  19482.507498
2022-01-28  23395.693488  13812.995058  33070.792859  19773.596463
2022-01-31  24006.923428  13934.876993  35171.119040  19636.874372
2022-02-01  23983.572944  13835.399573  35743.083983  19925.023296
2022-02-02  24152.520320  14046.003391  34233.472529  20177.889467
2022-02-03  23748.695651  13498.879637  32330.051257  20255.808481
2022-02-04  23708.812847  13709.036735  34636.660815  20163.186995
2022-02-07  23608.416466  13485.436928  33792.781101  20176.420582
2022-02-08  24044.386612  13647.198901  33736.521023  20144.077868
2022-02-09  24243.804829  13945.181700  35471.169214  20257.277366
2022-02-10  23671.679134  13549.515213  34767.934331  19865.970486
2022-02-11  23193.074994  13220.612812  33605.251084  19742.477441
2022-02-14  23226.082972  13218.820451  33464.602676  19364.558529
2022-02-15  23763.824045  13463.928593  34674.167534  19333.314641
2022-02-16  23730.818166  13448.212544  33980.311119  19220.235469
2022-02-17  23226.082972  13054.420637  33220.816157  18593.845690
2022-02-18  23008.785171  12928.693621  32180.027958  18501.597668
2022-02-22  22598.946078  12919.264540  30876.699881  18437.619439
2022-02-23  22014.443178  12584.742511  30717.298114  18162.364691
2022-02-24  22381.648278  13227.742518  32798.874512  18147.486271
2022-02-25  22671.836860  13349.876590  33089.546218  18476.304240
2022-02-28  22708.968475  13416.332357  33333.332737  18227.831103
2022-03-01  22444.910946  13243.908027  33342.711205  18055.238249
2022-03-02  22907.012146  13479.195180  32461.321196  18428.692614
2022-03-03  22861.626963  13287.463228  31401.783214  18736.680567
2022-03-04  22440.785211  13015.354561  31308.016417  18839.343597
2022-03-07  21908.544418  12523.676160  30398.498157  18757.510583
2022-03-08  21652.738359  12386.275501  30642.288253  18699.483949
2022-03-09  22410.528422  12954.288211  32226.909569  18779.828781
2022-03-10  21770.477097  12705.979032  31561.181404  18709.898957

In [90]:
weight = np.random.random(4)
weight /= weight.sum()
weight

array([0.31388069, 0.04006343, 0.45817405, 0.18788182])

In [91]:
weight.sum()

0.9999999999999999

In [92]:
np.sum((data/data.iloc[0])*portfolios*100000, axis=1)

Date
2022-01-03    100000.000000
2022-01-04     98019.456290
2022-01-05     95560.534226
2022-01-06     94708.416357
2022-01-07     94738.969443
2022-01-10     95062.722001
2022-01-11     95820.914859
2022-01-12     95751.560557
2022-01-13     93407.869546
2022-01-14     93446.069506
2022-01-18     91402.974339
2022-01-19     90790.027109
2022-01-20     90298.890064
2022-01-21     87238.135470
2022-01-24     87291.975853
2022-01-25     86921.908781
2022-01-26     86491.667066
2022-01-27     86517.842500
2022-01-28     90053.077867
2022-01-31     92749.793832
2022-02-01     93487.079796
2022-02-02     92609.885707
2022-02-03     89833.435026
2022-02-04     92217.697391
2022-02-07     91063.055076
2022-02-08     91572.184404
2022-02-09     93917.433109
2022-02-10     91855.099164
2022-02-11     89761.416331
2022-02-14     89274.064628
2022-02-15     91235.234813
2022-02-16     90379.577298
2022-02-17     88095.165456
2022-02-18     86619.104418
2022-02-22     84832.529938
2022-02-23     

In [93]:
np.sum((data/data.iloc[0])*weight*100000, axis=1)

Date
2022-01-03    100000.000000
2022-01-04     97862.429472
2022-01-05     95464.652291
2022-01-06     94630.081612
2022-01-07     94676.798692
2022-01-10     95032.828642
2022-01-11     95982.468451
2022-01-12     95758.536758
2022-01-13     93518.203817
2022-01-14     93379.388909
2022-01-18     91325.333532
2022-01-19     90583.689586
2022-01-20     90086.223985
2022-01-21     86812.324599
2022-01-24     86864.720718
2022-01-25     86502.649517
2022-01-26     85740.681551
2022-01-27     85693.068632
2022-01-28     89519.077198
2022-01-31     92596.393116
2022-02-01     93466.345141
2022-02-02     92243.095286
2022-02-03     89482.905426
2022-02-04     92044.024572
2022-02-07     90904.075743
2022-02-08     91399.825811
2022-02-09     93823.055630
2022-02-10     91825.953221
2022-02-11     89689.419704
2022-02-14     89214.259152
2022-02-15     91310.998425
2022-02-16     90364.366080
2022-02-17     88167.093372
2022-02-18     86581.876663
2022-02-22     84511.816438
2022-02-23     